### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by xorinzor** [ralscha/bread-compressor-cli#4]
I see you've been updating the package.json in the repository regularly, but the NPM package is still at 1.1.0.

Currently there's a moderate-severity vulnerability of `tough-cookie` via the `node-zopfli-es` package because it's still at 1.0.4 in the 1.1.0 release of this package.

Please update the NPM package to reflect the new changes.

**Comment by ralscha** [comment]
Version 2.0.0 published to NPM
